---
galaxy_info:
  author: Foo Bar
  description: Developer
  company: Foo Inc
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Fedora
      versions:
        - all
  galaxy_tags: []

dependencies: []
